[package.Linux]
version = "6.6.44"
description = "Ядро операционной системы."
home_page = "https://www.kernel.org"
download = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.44.tar.xz"
md5 = "613b7d75598dbf359b180c11acac39cc"

[package.crust]
version = "0.6"
description = "Низкоуровневый компонент для плат на базе Allwinner, предназначенный для уравления питанием. Во время глубокого сна ядра процессора, контроллер DRAM и большинство встроенных периферийных устройств отключаются от питания, что позволяет снизить электропотребление на >80%. На платах без PMIC crust также отвечает за упорядоченное включение и выключение устройства."
home_page = "https://github.com/crust-firmware/crust"
download = "https://raw.githubusercontent.com/Linux-for-ARM/packages/master/crust/crust-0.6.tar.gz"
md5 = "e558d2365411c82d0393e47e57aa7bea"

[package.musl]
version = "1.2.5"
description = "Минималистичная стандартная библиотека языка С."
home_page = "https://musl.libc.org"
download = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"
md5 = "ac5cfde7718d0547e224247ccfe59f18"

[package.BusyBox]
version = "1.36.1"
description = "Объединяет крошечные версии многих распространённых утилит UNIX в один небольшой двоичный файл (1-2 Мбайт). Он заменяет большинство утилит, которые обычно находятся в GNU Coreutils, GNU Findutils и т.д."
home_page = "https://www.busybox.net"
download = "https://busybox.net/downloads/busybox-1.36.1.tar.bz2"
md5 = "0fc591bc9f4e365dfd9ade0014f32561"

[package.binutils]
version = "2.43"
description = "Этот пакет содержит компоновщик, ассемблер и другие утилиты для работы с объектными файлами."
home_page = "https://www.gnu.org/software/binutils"
download = "https://sourceware.org/pub/binutils/releases/binutils-2.43.tar.xz"
md5 = "a54bb52cd75555416f316fbbe885925a"

[package."Wireless Tools"]
version = "29"
description = "Набор инструментов для работы с Wireless Extensions (WE — API ядра Linux, позволяющий драйверу передавать в пользовательское пространство конфигурацию и статистику, характерные для беспроводных локальных сетей)."
home_page = "https://hewlettpackard.github.io/wireless-tools/"
download = "https://hewlettpackard.github.io/wireless-tools/wireless_tools.29.tar.gz"
md5 = "e06c222e186f7cc013fd272d023710cb"

[package.u-boot]
version = "2023.10"
description = "Загрузчик операционной системы, предназначенный для встраиваемых систем на MIPS, ARM, PowerPC и т.д."
home_page = "https://source.denx.de/u-boot/u-boot"
download = "https://source.denx.de/u-boot/u-boot/-/archive/v2024.04/u-boot-v2024.04.tar.bz2"
md5 = "7267d5902ea37ee56e71162a53b331df"

[package.TF-A]
version = "2.10.3"
description = "Проект Trusted Firmware-A предоставляет эталонную реализацию безопасного программного обеспечения для процессоров класса ARMv7-A и ARMv8-A."
home_page = "https://www.trustedfirmware.org/projects/tf-a/"
download = "https://raw.githubusercontent.com/Linux-for-ARM/packages/master/tf-a/trusted-firmware-a.git-refs_tags_lts-v2.10.3.tar.gz"
md5 = "f8cf23ca23d6de58ff713bbbf87372fd"

[package.iana-etc]
version = "20241122"
description = "Данные для сетевых служб и сервисов. Необходим для обеспечения надлежащих сетевых возможностей."
home_page = "https://www.iana.org/protocols"
download = "https://github.com/Mic92/iana-etc/releases/download/20241122/iana-etc-20241122.tar.gz"
md5 = "38064a8e7c2233e23911ef9d39360584"

[package.MPC]
version = "1.3.1"
description = "Математические функции для комплексных чисел. Необходим для сборки GCC."
home_page = "http://www.multiprecision.org/"
download = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz"
md5 = "5c9bc658c9fd0f940e8e3e0f09530c62"

[package.rkbin]
version = "master"
description = "Прошивка BL31 для тех Rockchip SoC, для которых не обеспечена поддержка BL31 из состава TF-A."
home_page = "https://github.com/rockchip-linux/rkbin"
download = "https://raw.githubusercontent.com/Linux-for-ARM/packages/master/rkbin/rkbin-master.tar.xz"
md5 = "ad190429dc735449487d494f4696823f"

[package.GCC]
version = "13.2.0"
description = "Набор компиляторов GNU GCC."
home_page = "https://gcc.gnu.org"
download = "https://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz"
md5 = "24195dca80ded5e0551b533f46a4481d"

[package.GMP]
version = "6.3.0"
description = "Пакет с математическими библиотеками, которые предоставляют полезные функции для арифметики произвольной точности. Необходим для сборки GCC."
home_page = "https://gmplib.org"
download = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz"
md5 = "956dc04e864001a9c22429f761f2c283"

[package.MPFR]
version = "4.2.1"
description = "Функции для арифметики множественной точности. Необходим для сборки GCC."
home_page = "https://www.mpfr.org"
download = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz"
md5 = "523c50c6318dde6f9dc523bc0244690a"

[package."LFA Bootscripts"]
version = "1.0"
description = "Набор скриптов, используемых системой инициализации из BusyBox для запуска/остановки демонов и иных программ во время запуска/выключения LFA."
home_page = "https://github.com/Linux-for-ARM/lfa-bootscripts/"
download = "https://github.com/Linux-for-ARM/lfa-bootscripts/releases/download/v1.0/bootscripts-1.0.tar.xz"
md5 = "217d8f3d253f980691129e1c251379fc"
